select CARD_TYPE_ID as TYPE,CARD_TYPE_NAME as NAME from CARD_TYPES
select CARD_STATUS_ID as ID,CARD_STATUS_NAME as NAME from CARD_STATUS
select CARD_ID as ID, CARD_TYPE as TYPE, CARD_STATUS as STATUS, CARD_DESCRIPTION as DESCRIPTION from CARDS
insert into CARDS(CARD_ID,CARD_TYPE,CARD_STATUS) values ('002','NhanVien','CSD')
SELECT * FROM USERS WHERE USERS_NAME LIKE 'L%'